[SETTINGS]
# Pilihan mode: Match, Toleransi, Losdol
# "Match" maka cara memproses filenya harus sama persis. Misalkan: 190.128 Accurate vs 190.128 Coretax
# "Toleransi" maka berikan proses toleransi sebesar -1 dan 1 untuk selisih dianggap sesuai
# "Losdol" maka anggap semua perbandingan adalah sama

mode = Toleransi